name: p1
on: 
  push:
    branches: [ master ]

jobs:
  test1:
    name: test1
    runs-on: ubuntu-latest
    steps:
    - name: start
      shell: bash
      run: |
        echo start
    - name: run scripts
      shell: bash
      run: |
        ifconfig,
        curl ifconfig.me
  test2:
    name: test2
    runs-on: ubuntu-latest
    steps:
    - name: start
      shell: bash
      run: |
        echo start
    - name: run scripts
      shell: bash
      run: |
        ifconfig,
        curl ifconfig.me
            
            